# Generated by Django 2.2.7 on 2020-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_portfolio_template'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_portfolios',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='portfolios.Portfolio'),
        ),
    ]
