# Generated by Django 2.2.7 on 2020-03-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allowed_portfolios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_portfolios',
        ),
    ]
