# Generated by Django 2.2.7 on 2020-03-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_risk_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='risk_profiles',
        ),
    ]
