# Generated by Django 2.2.7 on 2020-03-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_risk_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AFSL',
        ),
        migrations.AddField(
            model_name='user',
            name='AFSL',
            field=models.ManyToManyField(blank=True, related_name='authorised_reps', to='users.AFSL'),
        ),
    ]
