# Generated by Django 2.2.7 on 2020-03-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0014_remove_riskprofilegroup_active'),
        ('users', '0006_auto_20200310_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='riskprofiles.RiskProfileGroup'),
        ),
    ]
