# Generated by Django 2.2.7 on 2020-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_active_rp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('share_all_clients', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='admin_practices',
            field=models.ManyToManyField(blank=True, related_name='admins', to='users.Practice'),
        ),
        migrations.AddField(
            model_name='user',
            name='practices',
            field=models.ManyToManyField(blank=True, related_name='staff', to='users.Practice'),
        ),
    ]
