# Generated by Django 2.2.7 on 2020-05-21 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0016_auto_20200428_1435'),
        ('users', '0009_auto_20200518_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='risk_profile_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='riskprofiles.RiskProfileGroup'),
        ),
    ]
