# Generated by Django 2.2.7 on 2020-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_auto_20200305_1019'),
        ('users', '0010_practice_risk_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='model_portfolios',
            field=models.ManyToManyField(blank=True, related_name='practices', to='portfolios.Portfolio'),
        ),
    ]
