# Generated by Django 2.2.7 on 2020-05-28 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='risk_profile_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_practices', to='riskprofiles.RiskProfileGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_staff', to='users.Practice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_rp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='riskprofiles.RiskProfileGroup'),
        ),
    ]
