# Generated by Django 2.2.7 on 2020-06-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_auto_20200618_1020'),
        ('users', '0019_auto_20200528_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='documents.Theme'),
        ),
    ]
