# Generated by Django 2.2.7 on 2020-06-24 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_theme_afsl_limitation'),
        ('users', '0020_user_active_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_practices', to='documents.Theme'),
        ),
    ]
