# Generated by Django 2.2.7 on 2020-09-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsl',
            name='AFSL_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='AFSL_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_ARN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
