# Generated by Django 2.2.7 on 2020-09-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200911_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='AFSL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_practices', to='users.AFSL'),
        ),
    ]
