# Generated by Django 2.2.7 on 2020-09-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_auto_20200526_1337'),
        ('documents', '0037_remove_theme_afsl_limitation'),
        ('riskprofiles', '0017_remove_riskprofilegroup_afsl_limitation'),
        ('users', '0025_practice_afsl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='share_all_clients',
        ),
        migrations.AddField(
            model_name='afsl',
            name='model_portfolios',
            field=models.ManyToManyField(blank=True, related_name='afsls', to='portfolios.Portfolio'),
        ),
        migrations.AddField(
            model_name='afsl',
            name='risk_profile_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afsls', to='riskprofiles.RiskProfileGroup'),
        ),
        migrations.AddField(
            model_name='afsl',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afsls', to='documents.Theme'),
        ),
    ]
