# Generated by Django 2.2.7 on 2020-09-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200915_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='remove_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
