# Generated by Django 2.2.7 on 2020-11-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_practice_remove_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
