# Generated by Django 2.2.7 on 2020-11-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20201103_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
