# Generated by Django 2.2.7 on 2020-01-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='investments',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='investments.Investment'),
        ),
    ]
