# Generated by Django 2.2.7 on 2020-01-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20200130_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='investments',
        ),
    ]
