# Generated by Django 2.2.7 on 2020-02-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0022_auto_20200214_1351'),
        ('portfolios', '0004_remove_portfolio_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='platform_fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.PlatformFees'),
        ),
    ]
