# Generated by Django 2.2.7 on 2020-02-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_portfolio_platform_fee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.Platform', to_field='id'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='platform_fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.PlatformFees', to_field='id'),
        ),
    ]
