# Generated by Django 2.2.7 on 2020-02-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20200215_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.Platform'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='platform_fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.PlatformFees'),
        ),
    ]
