# Generated by Django 2.2.7 on 2020-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20200215_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='auto_created',
            field=models.BooleanField(default=True),
        ),
    ]
