# Generated by Django 2.2.7 on 2020-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_portfolio_auto_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-auto_created',)},
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(auto_created=True), fields=('platform_fee_group',), name='unique_fee_group_default'),
        ),
    ]
