# Generated by Django 2.2.7 on 2020-03-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0030_auto_20200304_1227'),
        ('portfolios', '0009_auto_20200303_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInvestments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('investment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_portfolios', to='investments.InvestmentName')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_investments', to='portfolios.Portfolio')),
            ],
            options={
                'ordering': ('investment_name',),
            },
        ),
    ]
