# Generated by Django 2.2.7 on 2020-03-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0030_auto_20200304_1227'),
        ('portfolios', '0010_modelinvestments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelInvestments',
            new_name='ModelInvestment',
        ),
    ]
