# Generated by Django 2.2.7 on 2020-03-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_auto_20200304_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='platforms.Platform'),
        ),
    ]
