# Generated by Django 2.2.7 on 2020-03-04 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0013_portfolio_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
