# Generated by Django 2.2.7 on 2020-03-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_portfolio_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='model_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
