# Generated by Django 2.2.7 on 2020-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_auto_20200526_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='master_template',
            field=models.BooleanField(default=False),
        ),
    ]
