# Generated by Django 2.2.7 on 2021-02-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0069_auto_20201218_1338'),
        ('portfolios', '0019_portfolio_master_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='allowed_platforms',
            field=models.ManyToManyField(blank=True, related_name='allowed_portfolios', to='platforms.PlatformNames'),
        ),
    ]
