# Generated by Django 2.2.7 on 2020-01-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0010_auto_20200129_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAllocationNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('buy_spread', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('sell_spread', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('APIR_code', models.CharField(max_length=10)),
                ('ASX_code', models.CharField(max_length=10)),
                ('other_code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('investment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.InvestmentClass')),
                ('platform_limitation', models.ManyToManyField(related_name='platform_investments', to='platforms.PlatformNames')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='investments.AssetAllocationNames')),
            ],
        ),
    ]
