# Generated by Django 2.2.7 on 2020-01-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentFees',
        ),
        migrations.AddField(
            model_name='investment',
            name='buy_spread',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='sell_spread',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
