# Generated by Django 2.2.7 on 2020-01-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20200130_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAllocationNames',
            new_name='AssetAllocationName',
        ),
    ]
