# Generated by Django 2.2.7 on 2020-01-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20200130_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
