# Generated by Django 2.2.7 on 2020-01-30 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20200130_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='APIR_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='ASX_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.InvestmentClass'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='other_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='platform_limitation',
            field=models.ManyToManyField(blank=True, related_name='platform_investments', to='platforms.PlatformNames'),
        ),
    ]
