# Generated by Django 2.2.7 on 2020-01-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_assetallocation_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='portfolios',
        ),
    ]
