# Generated by Django 2.2.7 on 2020-01-31 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_remove_portfolio_investments'),
        ('investments', '0011_remove_investment_portfolios'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='portfolios.Portfolio'),
        ),
    ]
