# Generated by Django 2.2.7 on 2020-01-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_investment_portfolio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('name', 'template')},
        ),
    ]
