# Generated by Django 2.2.7 on 2020-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20200131_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(fields=('name', 'template'), name='unique_template_name'),
        ),
    ]
