# Generated by Django 2.2.7 on 2020-01-31 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20200131_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.InvestmentNames'),
        ),
    ]
