# Generated by Django 2.2.7 on 2020-01-31 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_auto_20200131_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentNames',
            new_name='InvestmentName',
        ),
    ]
