# Generated by Django 2.2.7 on 2020-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_auto_20200131_1308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investment',
            name='unique_template_name',
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(condition=models.Q(template=True), fields=('name',), name='unique_template_name'),
        ),
    ]
