# Generated by Django 2.2.7 on 2020-02-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0019_auto_20200207_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
        ),
    ]
