# Generated by Django 2.2.7 on 2020-02-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_auto_20200207_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAB_Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='investmentclass',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investmentname',
            name='name',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
