# Generated by Django 2.2.7 on 2020-02-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_auto_20200209_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NAB_Investment',
            new_name='NABInvestment',
        ),
    ]
