# Generated by Django 2.2.7 on 2020-02-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0022_auto_20200209_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentclass',
            name='TD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentclass',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
