# Generated by Django 2.2.7 on 2020-02-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0023_auto_20200210_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentclass',
            name='TD',
        ),
        migrations.RemoveField(
            model_name='investmentclass',
            name='cash',
        ),
        migrations.AddField(
            model_name='investment',
            name='TD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
