# Generated by Django 2.2.7 on 2020-02-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_investment_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='investment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='investments.Investment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='investments.AssetAllocationName'),
            preserve_default=False,
        ),
    ]
