# Generated by Django 2.2.7 on 2020-03-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_investment_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='platform_limitation',
        ),
    ]
