# Generated by Django 2.2.7 on 2020-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0032_auto_20200303_1530'),
        ('investments', '0028_remove_investment_platform_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='platform_limitation',
            field=models.ManyToManyField(blank=True, related_name='platform_investments', to='platforms.PlatformNames'),
        ),
    ]
