# Generated by Django 2.2.7 on 2020-03-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0029_investment_platform_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
