# Generated by Django 2.2.7 on 2020-03-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0032_auto_20200303_1530'),
        ('investments', '0030_auto_20200304_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='platform_fee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='platforms.PlatformFees'),
        ),
    ]
