# Generated by Django 2.2.7 on 2020-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0007_riskprofileaaname_active'),
        ('investments', '0031_investment_platform_fee_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocationname',
            name='rp_aaname_link',
            field=models.ManyToManyField(related_name='aa_links', to='riskprofiles.RiskProfileAAName'),
        ),
    ]
