# Generated by Django 2.2.7 on 2020-03-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0014_remove_riskprofilegroup_active'),
        ('investments', '0032_assetallocationname_rp_aaname_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='rp_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='riskprofiles.RiskProfileAAName'),
        ),
    ]
