# Generated by Django 2.2.7 on 2020-03-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0033_assetallocation_rp_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='investments.AssetAllocationName'),
        ),
    ]
