# Generated by Django 2.2.7 on 2020-05-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0035_auto_20200320_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_fee',
            new_name='_investment_fee',
        ),
    ]
