# Generated by Django 2.2.7 on 2020-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0036_auto_20200513_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='buy_spread',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sell_spread',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7),
        ),
    ]
