# Generated by Django 2.2.7 on 2020-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0038_auto_20200609_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentname',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investmentname',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='investmentname',
            constraint=models.UniqueConstraint(fields=('name', 'prefix'), name='unique_investment_name'),
        ),
    ]
