# Generated by Django 2.2.7 on 2020-07-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0051_auto_20200612_2053'),
        ('investments', '0039_auto_20200717_1656'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investmentname',
            name='unique_investment_name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='platform_limitation',
        ),
        migrations.RemoveField(
            model_name='investmentname',
            name='prefix',
        ),
        migrations.AddField(
            model_name='investmentname',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='platforms.PlatformNames'),
        ),
        migrations.AddConstraint(
            model_name='investmentname',
            constraint=models.UniqueConstraint(fields=('name', 'platform'), name='unique_investment_name'),
        ),
    ]
