# Generated by Django 2.2.7 on 2020-07-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0040_auto_20200717_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='investments.InvestmentClass'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='investments.InvestmentName'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='portfolios.Portfolio'),
        ),
    ]
