# Generated by Django 2.2.7 on 2020-07-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0041_auto_20200720_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentname',
            name='aa_link_root',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
