# Generated by Django 2.2.7 on 2020-07-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0042_investmentname_aa_link_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentname',
            name='aa_link_root',
        ),
    ]
