# Generated by Django 2.2.7 on 2020-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0043_remove_investmentname_aa_link_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocationname',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assetallocationname',
            name='rp_aaname_link',
            field=models.ManyToManyField(blank=True, related_name='aa_links', to='riskprofiles.RiskProfileAAName'),
        ),
    ]
