# Generated by Django 2.2.7 on 2020-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0047_investmentclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='APIR_code',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='ASX_code',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='other_code',
        ),
        migrations.AddField(
            model_name='investmentname',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
