# Generated by Django 2.2.7 on 2020-09-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0050_auto_20200921_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='clear_aa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investment',
            name='_investment_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7),
        ),
    ]
