# Generated by Django 2.2.7 on 2021-01-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0051_auto_20200923_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='override_fee_group',
            field=models.BooleanField(default=False),
        ),
    ]
