# Generated by Django 2.2.7 on 2020-02-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_scenario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['updated_at']},
        ),
    ]
