# Generated by Django 2.2.7 on 2020-02-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20200211_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='scenario_id',
            new_name='id',
        ),

    ]
