# Generated by Django 2.2.7 on 2020-04-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0014_remove_riskprofilegroup_active'),
        ('scenarios', '0004_auto_20200215_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='risk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='riskprofiles.RiskProfile'),
        ),
    ]
