# Generated by Django 2.2.7 on 2020-04-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_scenario_risk_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['-updated_at']},
        ),
    ]
