# Generated by Django 2.2.7 on 2020-05-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_active_practice'),
        ('scenarios', '0006_auto_20200422_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='users.Practice'),
        ),
    ]
