# Generated by Django 2.2.7 on 2020-06-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20200604_1506'),
        ('scenarios', '0008_auto_20200526_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='documents.Theme'),
        ),
    ]
