# Generated by Django 2.2.7 on 2020-06-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0009_scenario_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='generate_document',
            field=models.BooleanField(default=False),
        ),
    ]
