# Generated by Django 2.2.7 on 2020-07-14 03:03

from django.db import migrations, models
import django.db.models.deletion
import scenarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0010_scenario_generate_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=scenarios.models.Report.upload_path)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
        ),
    ]
