# Generated by Django 2.2.7 on 2020-07-15 05:35

from django.db import migrations, models
import scenarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(max_length=500, upload_to=scenarios.models.Report.upload_path),
        ),
    ]
