# Generated by Django 2.2.7 on 2020-07-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0013_report_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
