# Generated by Django 2.2.7 on 2020-07-16 10:09

from django.db import migrations, models
import scenarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0014_auto_20200715_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=scenarios.models.Report.upload_path),
        ),
    ]
