# Generated by Django 2.2.7 on 2020-09-15 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0015_auto_20200716_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='shared_scenarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
