# Generated by Django 2.2.7 on 2020-03-07 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_user_risk_profiles'),
        ('riskprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskprofileaaname',
            name='AFSL_limitation',
            field=models.ManyToManyField(blank=True, related_name='AFSL_aa_names', to='users.AFSL'),
        ),
        migrations.AddField(
            model_name='riskprofileaaname',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_aa_names', to=settings.AUTH_USER_MODEL),
        ),
    ]
