# Generated by Django 2.2.7 on 2020-03-07 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskprofiles', '0002_auto_20200307_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='risk_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
