# Generated by Django 2.2.7 on 2020-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0003_riskprofile_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='riskprofileaa',
            constraint=models.UniqueConstraint(fields=('name', 'riskprofile'), name='unique_name'),
        ),
    ]
