# Generated by Django 2.2.7 on 2020-03-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0004_auto_20200308_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofileaaname',
            name='asset_type',
            field=models.CharField(choices=[('Defensive', 'Defensive asset'), ('Growth', 'Growth asset'), ('Alternative', 'Alternative asset')], default='Growth', max_length=100),
            preserve_default=False,
        ),
    ]
