# Generated by Django 2.2.7 on 2020-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0005_riskprofileaaname_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofileaaname',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
