# Generated by Django 2.2.7 on 2020-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0006_riskprofileaaname_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofileaaname',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
