# Generated by Django 2.2.7 on 2020-03-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0007_riskprofileaaname_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofileaaname',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
