# Generated by Django 2.2.7 on 2020-03-11 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200310_1320'),
        ('riskprofiles', '0008_riskprofileaaname_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskprofile',
            name='AFSL_limitation',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='users',
        ),
        migrations.RemoveField(
            model_name='riskprofileaaname',
            name='AFSL_limitation',
        ),
        migrations.RemoveField(
            model_name='riskprofileaaname',
            name='active',
        ),
        migrations.RemoveField(
            model_name='riskprofileaaname',
            name='allowed_users',
        ),
        migrations.CreateModel(
            name='RiskProfileGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('AFSL_limitation', models.ManyToManyField(blank=True, related_name='risk_profiles', to='users.AFSL')),
                ('users', models.ManyToManyField(blank=True, related_name='risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='riskprofiles.RiskProfileGroup'),
        ),
        migrations.AddField(
            model_name='riskprofileaaname',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_aa_names', to='riskprofiles.RiskProfileGroup'),
        ),
    ]
