# Generated by Django 2.2.7 on 2020-03-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0010_auto_20200311_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofilegroup',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
