# Generated by Django 2.2.7 on 2020-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0012_auto_20200311_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofilegroup',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
