# Generated by Django 2.2.7 on 2020-04-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0014_remove_riskprofilegroup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofileaaname',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
