# Generated by Django 2.2.7 on 2020-04-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofiles', '0015_riskprofileaaname_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskprofileaaname',
            options={'ordering': ['order']},
        ),
    ]
