# Generated by Django 2.2.7 on 2020-07-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0038_auto_20200609_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
                ('aa_link_root', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapes', to='investments.InvestmentName')),
            ],
        ),
    ]
