# Generated by Django 2.2.7 on 2020-07-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrape',
            name='aa_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentscrape',
            name='aa_link_root',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
