# Generated by Django 2.2.7 on 2020-07-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0002_auto_20200720_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentscrape',
            name='aa_link_root',
        ),
    ]
