# Generated by Django 2.2.7 on 2020-07-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0005_investmentscrape_prerender_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_aa_allocation_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_aa_name_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_aa_root',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
