# Generated by Django 2.2.7 on 2020-07-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0006_auto_20200722_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='fee_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
