# Generated by Django 2.2.7 on 2020-07-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0007_auto_20200723_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentscrape',
            name='aa_path',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentscrape',
            name='fee_path',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
