# Generated by Django 2.2.7 on 2020-07-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0009_auto_20200723_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrape',
            name='split_fee_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='use_regex_fee_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_fee_root',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
