# Generated by Django 2.2.7 on 2020-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0010_auto_20200724_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentscrape',
            old_name='use_regex_fee_percentage',
            new_name='bs_use_regex_percentage',
        ),
        migrations.RenameField(
            model_name='investmentscrape',
            old_name='split_fee_name_string',
            new_name='fee_split_name_string',
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='fee_use_regex_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_bs_root',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
