# Generated by Django 2.2.7 on 2020-07-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0011_auto_20200724_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentscrape',
            old_name='fee_use_regex_percentage',
            new_name='fee_use_percentage_regex',
        ),
    ]
