# Generated by Django 2.2.7 on 2020-07-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0012_auto_20200724_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrape',
            name='bs_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='bs_prerender_js',
            field=models.BooleanField(default=False),
        ),
    ]
