# Generated by Django 2.2.7 on 2020-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0013_auto_20200724_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
