# Generated by Django 2.2.7 on 2020-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0014_bsroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrape',
            name='xpath_bs_node',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
