# Generated by Django 2.2.7 on 2020-07-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0054_platformnames_bs_link_root'),
        ('scrapes', '0015_investmentscrape_xpath_bs_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentScrapeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_root', models.URLField(blank=True, max_length=300, null=True)),
                ('aa_prerender_js', models.BooleanField(default=False)),
                ('aa_path', models.CharField(blank=True, max_length=100)),
                ('fee_root', models.URLField(blank=True, max_length=300, null=True)),
                ('fee_prerender_js', models.BooleanField(default=False)),
                ('fee_path', models.CharField(blank=True, max_length=100)),
                ('bs_root', models.URLField(blank=True, max_length=300, null=True)),
                ('bs_prerender_js', models.BooleanField(default=False)),
                ('bs_path', models.CharField(blank=True, max_length=100)),
                ('xpath_aa_root', models.CharField(blank=True, max_length=300, null=True)),
                ('xpath_aa_name_path', models.CharField(blank=True, max_length=300, null=True)),
                ('xpath_aa_allocation_path', models.CharField(blank=True, max_length=300, null=True)),
                ('xpath_fee_root', models.CharField(blank=True, max_length=300, null=True)),
                ('fee_split_name_string', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_use_percentage_regex', models.BooleanField(default=False)),
                ('xpath_bs_root', models.CharField(blank=True, max_length=300, null=True)),
                ('xpath_bs_node', models.CharField(blank=True, max_length=300, null=True)),
                ('bs_use_regex_percentage', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_settings', to='platforms.PlatformNames')),
            ],
        ),
        migrations.AddField(
            model_name='investmentscrape',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='scrapes.InvestmentScrapeSettings'),
        ),
    ]
