# Generated by Django 2.2.7 on 2020-07-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0016_auto_20200727_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentscrapesettings',
            name='aa_path',
        ),
        migrations.RemoveField(
            model_name='investmentscrapesettings',
            name='bs_path',
        ),
        migrations.RemoveField(
            model_name='investmentscrapesettings',
            name='fee_path',
        ),
    ]
