# Generated by Django 2.2.7 on 2020-07-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0017_auto_20200727_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentscrape',
            name='aa_prerender_js',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='bs_prerender_js',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='bs_use_regex_percentage',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='fee_prerender_js',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='fee_split_name_string',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='fee_use_percentage_regex',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_aa_allocation_path',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_aa_name_path',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_aa_root',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_bs_node',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_bs_root',
        ),
        migrations.RemoveField(
            model_name='investmentscrape',
            name='xpath_fee_root',
        ),
    ]
