# Generated by Django 2.2.7 on 2020-07-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0055_auto_20200727_1655'),
        ('scrapes', '0018_auto_20200727_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AARoot',
        ),
        migrations.DeleteModel(
            name='BSRoot',
        ),
        migrations.DeleteModel(
            name='FeeRoot',
        ),
    ]
