# Generated by Django 2.2.7 on 2020-07-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0019_auto_20200727_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_fee_name_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_fee_node',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_fee_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
