# Generated by Django 2.2.7 on 2020-07-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0021_auto_20200728_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentscrapesettings',
            old_name='xpath_bs_path',
            new_name='xpath_bs_buy_path',
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_bs_sell_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
