# Generated by Django 2.2.7 on 2020-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0023_auto_20200728_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_slugify_path',
            field=models.BooleanField(default=False),
        ),
    ]
