# Generated by Django 2.2.7 on 2020-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0024_investmentscrapesettings_aa_slugify_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_slugify_path_no_hyphens',
            field=models.BooleanField(default=False),
        ),
    ]
