# Generated by Django 2.2.7 on 2020-07-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0027_auto_20200731_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_pdf_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_pdf_mod_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
