# Generated by Django 2.2.7 on 2020-08-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0028_auto_20200731_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_pdf_pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
