# Generated by Django 2.2.7 on 2020-08-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0029_investmentscrapesettings_aa_pdf_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='fee_pdf_pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
