# Generated by Django 2.2.7 on 2020-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0030_investmentscrapesettings_fee_pdf_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_pdf_tables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='fee_pdf_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='fee_pdf_mod_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='fee_pdf_tables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
