# Generated by Django 2.2.7 on 2020-08-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0032_auto_20200803_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='camelotsettings',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='scrapes.InvestmentScrapeSettings'),
        ),
    ]
