# Generated by Django 2.2.7 on 2020-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0034_camelotsettings_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camelotsettings',
            name='pdf_pages',
        ),
        migrations.AddField(
            model_name='camelotsettings',
            name='flavor',
            field=models.CharField(default='lattice', max_length=10),
        ),
        migrations.AddField(
            model_name='camelotsettings',
            name='pages',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='camelotsettings',
            name='row_tol',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='camelotsettings',
            name='strip_text',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='camelotsettings',
            name='table_areas',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='camelotsettings',
            name='type',
            field=models.CharField(blank=True, choices=[('aa', 'aa'), ('fee', 'fee'), ('bs', 'bs')], max_length=10, null=True),
        ),
    ]
