# Generated by Django 2.2.7 on 2020-08-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0036_auto_20200803_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='camelotsettings',
            name='process_background',
            field=models.BooleanField(default=False),
        ),
    ]
