# Generated by Django 2.2.7 on 2020-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0037_camelotsettings_process_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_aa_node',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
