# Generated by Django 2.2.7 on 2020-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0038_investmentscrapesettings_xpath_aa_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_split_name_string',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
