# Generated by Django 2.2.7 on 2020-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0039_investmentscrapesettings_aa_split_name_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentscrapesettings',
            name='aa_split_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
