# Generated by Django 2.2.7 on 2020-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0040_auto_20200804_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_use_percentage_regex',
            field=models.BooleanField(default=False),
        ),
    ]
