# Generated by Django 2.2.7 on 2020-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0041_investmentscrapesettings_aa_use_percentage_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
