# Generated by Django 2.2.7 on 2020-08-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0042_investmentscrapesettings_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_camelot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bs_settings', to='scrapes.CamelotSettings'),
        ),
    ]
