# Generated by Django 2.2.7 on 2020-08-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0043_investmentscrapesettings_bs_camelot'),
    ]

    operations = [
        migrations.AddField(
            model_name='camelotsettings',
            name='line_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
