# Generated by Django 2.2.7 on 2020-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0044_camelotsettings_line_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_aa_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_bs_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_fee_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
