# Generated by Django 2.2.7 on 2020-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0045_auto_20200805_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='xpath_aa_inv_name_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
