# Generated by Django 2.2.7 on 2020-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0046_investmentscrapesettings_xpath_aa_inv_name_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_pdf_grid_style',
            field=models.BooleanField(default=False),
        ),
    ]
