# Generated by Django 2.2.7 on 2020-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0047_investmentscrapesettings_aa_pdf_grid_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_split_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
