# Generated by Django 2.2.7 on 2020-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0050_auto_20200818_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='capitalise_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='strings_to_remove',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
