# Generated by Django 2.2.7 on 2020-08-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0051_auto_20200819_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_split_inv_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
