# Generated by Django 2.2.7 on 2020-08-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0052_investmentscrapesettings_aa_split_inv_name_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_pdf_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_pdf_mod_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_pdf_tables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
