# Generated by Django 2.2.7 on 2020-08-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0053_auto_20200819_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='aa_excise_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='bs_excise_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investmentscrapesettings',
            name='fee_excise_name_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
