# Generated by Django 2.2.7 on 2020-11-24 01:54

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0056_platformscrapesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformscrapesettings',
            old_name='aa_url',
            new_name='xpath_url',
        ),
        migrations.AddField(
            model_name='platformscrapesettings',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformscrapesettings',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
