# Generated by Django 2.2.7 on 2020-11-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0057_auto_20201124_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformscrapesettings',
            name='keep_url_args',
            field=models.BooleanField(default=False),
        ),
    ]
