# Generated by Django 2.2.7 on 2020-11-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0058_platformscrapesettings_keep_url_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformscrapesettings',
            name='next_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
