# Generated by Django 2.2.7 on 2020-11-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0059_platformscrapesettings_next_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformscrapesettings',
            name='direct_link',
            field=models.BooleanField(default=False),
        ),
    ]
