# Generated by Django 2.2.7 on 2020-12-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0060_platformscrapesettings_direct_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformscrapesettings',
            name='excise_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
