# Generated by Django 2.2.7 on 2021-01-19 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0069_auto_20201218_1338'),
        ('scrapes', '0061_platformscrapesettings_excise_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplScrapeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
                ('next_check', models.DateTimeField(blank=True, null=True)),
                ('root', models.URLField(blank=True, max_length=300, null=True)),
                ('prerender_js', models.BooleanField(default=False)),
                ('pdf', models.BooleanField(default=True)),
                ('pdf_manual', models.BooleanField(default=True)),
                ('pdf_mod_date', models.CharField(default='', max_length=100)),
                ('xpath_url', models.CharField(blank=True, max_length=300, null=True)),
                ('keep_url_args', models.BooleanField(default=False)),
                ('direct_link', models.BooleanField(default=False)),
                ('excise_string', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apl_scrape_settings', to='platforms.PlatformNames')),
            ],
        ),
    ]
