# Generated by Django 2.2.7 on 2020-06-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0008_auto_20200526_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_bold', models.BooleanField(default=False)),
                ('font_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('font_italic', models.BooleanField(default=False)),
                ('font_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('font_smallcaps', models.BooleanField(default=False)),
                ('font_type', models.CharField(blank=True, max_length=50, null=True)),
                ('border_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('border_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('background_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('bullet_items', models.BooleanField(default=False)),
                ('bullet_style', models.CharField(default='hyphen', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_platforms_as_cols', models.BooleanField(default=True)),
                ('display_alternate_platform', models.BooleanField(default=False)),
                ('display_aggregated_total', models.BooleanField(default=True)),
                ('display_percentage_subtotal', models.BooleanField(default=False)),
                ('display_percentage_total', models.BooleanField(default=False)),
                ('display_one_off_fees', models.BooleanField(default=True)),
                ('display_aa_summary', models.BooleanField(default=False)),
                ('display_investment_names', models.BooleanField(default=False)),
                ('display_differences', models.BooleanField(default=False)),
                ('full_width_subheader1', models.BooleanField(default=False)),
                ('full_width_subheader2', models.BooleanField(default=False)),
                ('split_platform_types', models.BooleanField(default=False)),
                ('percentage_position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Bottom', 'Bottom')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_bold', models.BooleanField(default=False)),
                ('font_colour', models.CharField(default='black', max_length=50)),
                ('font_italic', models.BooleanField(default=False)),
                ('font_size', models.PositiveSmallIntegerField()),
                ('font_smallcaps', models.BooleanField(default=False)),
                ('font_type', models.CharField(default='Calibri', max_length=50)),
                ('border_colour', models.CharField(default='black', max_length=50)),
                ('border_width', models.PositiveSmallIntegerField()),
                ('background_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_margin_top', models.DecimalField(decimal_places=3, default=56.693, max_digits=8)),
                ('cell_margin_bottom', models.PositiveSmallIntegerField(default=56.693)),
                ('cell_margin_start', models.PositiveSmallIntegerField(default=113.389)),
                ('cell_margin_end', models.PositiveSmallIntegerField(default=113.389)),
                ('border_top', models.BooleanField(default=True)),
                ('border_bottom', models.BooleanField(default=True)),
                ('border_start', models.BooleanField(default=True)),
                ('border_end', models.BooleanField(default=True)),
                ('border_inner_vertical', models.BooleanField(default=True)),
                ('border_inner_horizontal', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BooleanField(default=False)),
                ('column_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_header_styles', to='documents.Element')),
                ('normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normal_styles', to='documents.Element')),
                ('subheader1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subheader1_styles', to='documents.Element')),
                ('subheader2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subheader2_styles', to='documents.Element')),
                ('subtotal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtotal_styles', to='documents.Element')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_styles', to='documents.Table')),
                ('total', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_styles', to='documents.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_documents', to='documents.Format')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scenarios.Scenario')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_documents', to='documents.Style')),
            ],
        ),
    ]
