# Generated by Django 2.2.7 on 2020-06-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='Structure',
        ),
        migrations.RemoveField(
            model_name='document',
            name='format',
        ),
        migrations.RemoveField(
            model_name='style',
            name='template',
        ),
        migrations.AddField(
            model_name='document',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_documents', to='documents.Structure'),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
