# Generated by Django 2.2.7 on 2020-06-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200601_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='column_header',
        ),
        migrations.RemoveField(
            model_name='style',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='style',
            name='subheader1',
        ),
        migrations.RemoveField(
            model_name='style',
            name='subheader2',
        ),
        migrations.RemoveField(
            model_name='style',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='style',
            name='table',
        ),
        migrations.RemoveField(
            model_name='style',
            name='total',
        ),
        migrations.AddField(
            model_name='element',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='documents.Style'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Header', 'Header'), ('Subheader1', 'Subheader1'), ('Subheader2', 'Subheader2'), ('Normal', 'Normal'), ('Subtotal', 'Subtotal'), ('Total', 'Total')], default='Header', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='background_colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_bottom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_colour',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='border_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_inner_horizontal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_inner_vertical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_top',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='cell_margin_bottom',
            field=models.PositiveSmallIntegerField(default=56.693),
        ),
        migrations.AddField(
            model_name='style',
            name='cell_margin_end',
            field=models.PositiveSmallIntegerField(default=113.389),
        ),
        migrations.AddField(
            model_name='style',
            name='cell_margin_start',
            field=models.PositiveSmallIntegerField(default=113.389),
        ),
        migrations.AddField(
            model_name='style',
            name='cell_margin_top',
            field=models.DecimalField(decimal_places=3, default=56.693, max_digits=8),
        ),
        migrations.AddField(
            model_name='style',
            name='font_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='font_colour',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='font_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='font_smallcaps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='font_type',
            field=models.CharField(default='Calibri', max_length=50),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
