# Generated by Django 2.2.7 on 2020-06-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_generate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.Structure'),
        ),
        migrations.AlterField(
            model_name='document',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.Style'),
        ),
    ]
