# Generated by Django 2.2.7 on 2020-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20200602_1606'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_order_per_table',
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('order', 'table_type', 'document'), name='unique_order_per_table'),
        ),
    ]
