# Generated by Django 2.2.7 on 2020-06-02 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0008_auto_20200526_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0008_auto_20200602_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.BooleanField(default=False)),
                ('generate', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_order_per_table',
        ),
        migrations.RemoveField(
            model_name='content',
            name='document',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='document',
        ),
        migrations.RemoveField(
            model_name='style',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='theme',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='scenarios.Scenario'),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='documents.Theme'),
        ),
        migrations.AddField(
            model_name='structure',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='documents.Theme'),
        ),
        migrations.AddField(
            model_name='style',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='documents.Theme'),
        ),
    ]
