# Generated by Django 2.2.7 on 2020-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20200603_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='font_colour',
            new_name='font_color',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='font_type',
            new_name='font_name',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='font_smallcaps',
            new_name='font_small_caps',
        ),
        migrations.AddField(
            model_name='element',
            name='font_underline',
            field=models.BooleanField(default=False),
        ),
    ]
