# Generated by Django 2.2.7 on 2020-06-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20200603_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
