# Generated by Django 2.2.7 on 2020-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_theme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_color',
            field=models.CharField(default='0,0,0', max_length=20),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_size',
            field=models.PositiveIntegerField(),
        ),
    ]
