# Generated by Django 2.2.7 on 2020-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20200603_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='background_colour',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='border_colour',
            new_name='border_color',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='background_colour',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='border_colour',
            new_name='border_color',
        ),
        migrations.AlterField(
            model_name='element',
            name='font_bold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='font_italic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='font_small_caps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='font_underline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_size',
            field=models.PositiveIntegerField(default=139700),
        ),
    ]
