# Generated by Django 2.2.7 on 2020-06-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20200604_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='border_sides',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
