# Generated by Django 2.2.7 on 2020-06-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_element_border_sides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='scenario',
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Status', 'Status'), ('Product', 'Product'), ('Balance', 'Balance'), ('Investments', 'Investments'), ('One-off Fees Subheader', 'One-off Fees Subheader'), ('One-off Fees Content', 'One-off Fees Content'), ('Ongoing Fees Subheader', 'Ongoing Fees Subheader'), ('Ongoing Fees Content', 'Ongoing Fees Content'), ('Subtotal', 'Subtotal'), ('Adviser Fee', 'Adviser Fee'), ('Total', 'Total')], max_length=20),
        ),
        migrations.AlterField(
            model_name='element',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='style',
            name='border_color',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='style',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
