# Generated by Django 2.2.7 on 2020-06-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20200604_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='generate',
        ),
    ]
