# Generated by Django 2.2.7 on 2020-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_remove_theme_generate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Status', 'Status'), ('Product', 'Product'), ('Balance', 'Balance'), ('Investments', 'Investments'), ('One-off Fees Subheader', 'One-off Fees Subheader'), ('One-off Fees Content', 'One-off Fees Content'), ('Ongoing Fees Subheader', 'Ongoing Fees Subheader'), ('Ongoing Fees Content', 'Ongoing Fees Content'), ('Subtotal', 'Subtotal'), ('Adviser Fee', 'Adviser Fee'), ('Total', 'Total')], max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('rowHeader', 'rowHeader'), ('rowSubheader1', 'rowSubheader1'), ('rowSubheader2', 'rowSubheader2'), ('rowSubtotal', 'rowSubtotal'), ('rowNormal1', 'rowNormal1'), ('rowNormal2', 'rowNormal2'), ('rowTotal', 'rowTotal')], max_length=20),
        ),
    ]
