# Generated by Django 2.2.7 on 2020-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20200609_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='display_NA_flat_fees',
            field=models.BooleanField(default=False),
        ),
    ]
