# Generated by Django 2.2.7 on 2020-06-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_structure_display_na_flat_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='display_null_rows',
            field=models.BooleanField(default=False),
        ),
    ]
