# Generated by Django 2.2.7 on 2020-06-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_structure_display_null_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='display_one_off_fees',
        ),
    ]
