# Generated by Django 2.2.7 on 2020-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_remove_structure_display_investment_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='display_aa_summary',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='display_aggregated_total',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='display_differences',
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Status', 'Status'), ('Product', 'Product'), ('Balance', 'Balance'), ('Investments', 'Investments'), ('One-off Fees Subheader', 'One-off Fees Subheader'), ('Switch Fees', 'Switch Fees'), ('Buy/Sell Fees', 'Buy/Sell Fees'), ('One-off Subtotal', 'One-off Subtotal'), ('Ongoing Fees Subheader', 'Ongoing Fees Subheader'), ('Ongoing Fees Content', 'Ongoing Fees Content'), ('Subtotal', 'Subtotal'), ('Adviser Fee', 'Adviser Fee'), ('Total', 'Total'), ('Aggregated Total', 'Aggregated Total'), ('AA Summary', 'AA Summary')], max_length=50),
        ),
    ]
