# Generated by Django 2.2.7 on 2020-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_auto_20200611_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='hide_bar_chart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='hide_risk_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structure',
            name='hide_variance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Status', 'Status'), ('Product', 'Product'), ('Balance', 'Balance'), ('Investments', 'Investments'), ('One-off Fees Subheader', 'One-off Fees Subheader'), ('Switch Fees', 'Switch Fees'), ('Buy/Sell Fees', 'Buy/Sell Fees'), ('One-off Subtotal', 'One-off Subtotal'), ('Ongoing Fees Subheader', 'Ongoing Fees Subheader'), ('Ongoing Fees Content', 'Ongoing Fees Content'), ('Subtotal', 'Subtotal'), ('Adviser Fee', 'Adviser Fee'), ('Total', 'Total'), ('Aggregated Total', 'Aggregated Total'), ('AA Summary', 'AA Summary'), ('Status', 'Status'), ('Defensive Subheader', 'Defensive Subheader'), ('Defensive Content', 'Defensive Content'), ('Defensive Subtotal', 'Defensive Subtotal'), ('Growth Subheader', 'Growth Subheader'), ('Growth Content', 'Growth Content'), ('Growth Subtotal', 'Growth Subtotal'), ('Alternative Subheader', 'Alternative Subheader'), ('Alternative Content', 'Alternative Content'), ('Alternative Subtotal', 'Alternative Subtotal'), ('Total', 'Total')], max_length=50),
        ),
    ]
