# Generated by Django 2.2.7 on 2020-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20200616_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='include_cur_vs_rec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='include_cur_vs_rp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='include_cur_vs_rp_vs_rec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='include_rec_vs_rp',
            field=models.BooleanField(default=True),
        ),
    ]
