# Generated by Django 2.2.7 on 2020-06-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_auto_20200617_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='hide_ICR',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='hide_percentage',
            field=models.BooleanField(default=True),
        ),
    ]
