# Generated by Django 2.2.7 on 2020-09-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_auto_20200714_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='AFSL_limitation',
        ),
    ]
