# Generated by Django 2.2.7 on 2020-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_remove_theme_afsl_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
