# Generated by Django 2.2.7 on 2020-10-15 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_auto_20200921_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='documents.Style'),
        ),
    ]
