# Generated by Django 2.2.7 on 2020-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_auto_20201015_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('rowHeader', 'rowHeader'), ('rowSubheader1', 'rowSubheader1'), ('rowSubheader2', 'rowSubheader2'), ('rowSubtotal', 'rowSubtotal'), ('rowNormal1', 'rowNormal1'), ('rowNormal2', 'rowNormal2'), ('rowTotal', 'rowTotal')], max_length=30),
        ),
    ]
