# Generated by Django 2.2.7 on 2020-10-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_auto_20201015_1607'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_order_per_table',
        ),
    ]
