# Generated by Django 2.2.7 on 2020-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_auto_20201016_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='style',
            name='border_sides',
            field=models.CharField(default='top,bottom,insideV,insideH', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_color',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='style',
            name='font_size',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
