# Generated by Django 2.2.7 on 2020-10-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
