# Generated by Django 2.2.7 on 2020-01-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('platforms', '0002_platform_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('admin_fee_structure', models.CharField(blank=True, choices=[('Flat percentange', 'Flat percentage admin fee'), ('Tiered', 'Tiered admin fee'), ('Tiered per asset', 'Tiered admin fee per asset'), ('Staggered', 'Staggered admin fee'), ('MLC Wrap', 'MLC Wrap custom admin fee')], max_length=100)),
                ('admin_fee_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('admin_fee_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('admin_fee_rebate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expense_recovery_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expense_recovery_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('ORR_levy', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('fund_accounting_fee_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fund_accounting_fee_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('trustee_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('issuer_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('sma_admin_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cash_fee', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('switch_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('minimum_admin_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maximum_admin_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimum_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maximum_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('admin_fee_cutoff', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('white_label_admin_fee', models.BooleanField(default=False)),
                ('admin_fee_exclusions', models.CharField(blank=True, choices=[('Cash', 'Cash only excluded'), ('TD', 'Term deposits only excluded'), ('Cash and TD', 'Cash and TDs excluded')], max_length=50)),
                ('AFSL_limitation', models.ManyToManyField(blank=True, related_name='platforms', to='users.AFSL')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='platforms.Platform')),
            ],
        ),
    ]
