# Generated by Django 2.2.7 on 2020-01-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20200127_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformfees',
            old_name='id',
            new_name='platform_fee_id'
        ),
    ]
