# Generated by Django 2.2.7 on 2020-01-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_auto_20200127_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='platform_fee_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
