# Generated by Django 2.2.7 on 2020-01-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_auto_20200127_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfees',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
