# Generated by Django 2.2.7 on 2020-01-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_auto_20200129_1442'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('name', 'template'), name='unique_platform_template'),
        ),
    ]
