# Generated by Django 2.2.7 on 2020-02-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_auto_20200207_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='USI',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
