# Generated by Django 2.2.7 on 2020-02-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_platformnames_usi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformtierthresholds',
            options={'ordering': ['-threshold']},
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='platform',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='platforms.Platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformtierpercs',
            name='platform_fee_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tier_percs', to='platforms.PlatformFees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformtierthresholds',
            name='platform_fee_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tier_thresholds', to='platforms.PlatformFees'),
            preserve_default=False,
        ),
    ]
