# Generated by Django 2.2.7 on 2020-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_auto_20200209_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformfees',
            old_name='ORR_levy',
            new_name='_ORR_levy',
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='minimum_admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='minimum_total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
