# Generated by Django 2.2.7 on 2020-02-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0020_platform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platform',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
