# Generated by Django 2.2.7 on 2020-02-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0021_auto_20200212_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfees',
            name='_ORR_levy',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
        ),
    ]
