# Generated by Django 2.2.7 on 2020-02-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0022_auto_20200214_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platform_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='platformfamilygroups',
            old_name='platformfamilygroup_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='platformfees',
            old_name='platform_fee_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='platformnames',
            old_name='platformname_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='platform',
            name='fee_link_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='platforms.PlatformFamilyGroups', to_field='id'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='platforms.PlatformNames', to_field='id'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='scenario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='scenarios.Scenario', to_field='scenario_id'),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='platforms.Platform', to_field='id'),
        ),
        migrations.AlterField(
            model_name='platformtierpercs',
            name='platform_fee_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_percs', to='platforms.PlatformFees', to_field='id'),
        ),
        migrations.AlterField(
            model_name='platformtierthresholds',
            name='platform_fee_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_thresholds', to='platforms.PlatformFees', to_field='id'),
        ),
    ]
