# Generated by Django 2.2.7 on 2020-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0025_auto_20200220_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='ORR_levy_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='admin_fee_cutoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='white_label_admin_fee',
            field=models.BooleanField(default=False),
        ),
    ]
