# Generated by Django 2.2.7 on 2020-02-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0028_auto_20200221_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnames',
            name='name',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
