# Generated by Django 2.2.7 on 2020-03-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0030_auto_20200221_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformfees',
            options={'ordering': ('fee_group_order',)},
        ),
        migrations.AddField(
            model_name='platform',
            name='single_fee_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformfees',
            name='fee_group_order',
            field=models.IntegerField(default=0),
        ),
    ]
