# Generated by Django 2.2.7 on 2020-03-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0031_auto_20200303_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='scenarios.Scenario'),
        ),
    ]
