# Generated by Django 2.2.7 on 2020-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0032_auto_20200303_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfees',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
