# Generated by Django 2.2.7 on 2020-04-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0035_auto_20200327_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='slug',
        ),
    ]
