# Generated by Django 2.2.7 on 2020-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0038_platform_clone_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platform',
            name='fee_link_type',
            field=models.CharField(choices=[('None', 'No change in admin fee'), ('Combined', 'Admin fee calculated on combined balance'), ('Reduction', 'Admin fee reduced by fixed amount')], default='None', max_length=20),
        ),
    ]
