# Generated by Django 2.2.7 on 2020-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0039_auto_20200504_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
