# Generated by Django 2.2.7 on 2020-05-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0040_auto_20200505_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfees',
            name='cash_fee',
        ),
        migrations.RemoveField(
            model_name='platformfees',
            name='switch_fee',
        ),
    ]
