# Generated by Django 2.2.7 on 2020-05-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0041_auto_20200506_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='cash_fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='switch_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
