# Generated by Django 2.2.7 on 2020-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0042_auto_20200506_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='manual_linking_adjustment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
