# Generated by Django 2.2.7 on 2020-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0043_platform_manual_linking_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='custom_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
