# Generated by Django 2.2.7 on 2020-06-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0045_platform_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='adviser_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='adviser_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
