# Generated by Django 2.2.7 on 2020-06-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0047_auto_20200605_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_adviser_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_adviser_fee_percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
    ]
