# Generated by Django 2.2.7 on 2020-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0048_auto_20200605_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
