# Generated by Django 2.2.7 on 2020-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0049_platform_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='switch_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
