# Generated by Django 2.2.7 on 2020-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0050_auto_20200611_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('Accumulation', 'Superannuation - Accumulation'), ('Pension', 'Superannuation - Pension'), ('Defined Benefit', 'Superannuation - Defined Benefit'), ('Investment', 'Investment'), ('SMSF - Accumulation', 'Self Managed Super Fund - Accumulation'), ('SMSF - Pension', 'Self Managed Super Fund - Pension')], max_length=100, null=True),
        ),
    ]
