# Generated by Django 2.2.7 on 2020-07-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0004_aaroot'),
        ('platforms', '0051_auto_20200612_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='aa_link_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_names', to='scrapes.AARoot'),
        ),
    ]
