# Generated by Django 2.2.7 on 2020-07-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0007_auto_20200723_1342'),
        ('platforms', '0052_platformnames_aa_link_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='fee_link_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_names', to='scrapes.FeeRoot'),
        ),
    ]
