# Generated by Django 2.2.7 on 2020-07-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0014_bsroot'),
        ('platforms', '0053_platformnames_fee_link_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='bs_link_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_names', to='scrapes.BSRoot'),
        ),
    ]
