# Generated by Django 2.2.7 on 2020-07-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0054_platformnames_bs_link_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformnames',
            name='aa_link_root',
        ),
        migrations.RemoveField(
            model_name='platformnames',
            name='bs_link_root',
        ),
        migrations.RemoveField(
            model_name='platformnames',
            name='fee_link_root',
        ),
    ]
