# Generated by Django 2.2.7 on 2020-09-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_practice_afsl'),
        ('platforms', '0056_platformnames_investment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfees',
            name='AFSL_limitation',
        ),
        migrations.AddField(
            model_name='platformfees',
            name='AFSL_limitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fees', to='users.AFSL'),
        ),
    ]
