# Generated by Django 2.2.7 on 2020-10-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0057_auto_20200914_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='maximum_linked_accounts',
        ),
    ]
