# Generated by Django 2.2.7 on 2020-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0058_remove_platform_maximum_linked_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfees',
            name='maximum_admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='maximum_total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
