# Generated by Django 2.2.7 on 2020-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0059_auto_20201009_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfees',
            name='admin_fee_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='admin_fee_percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='expense_recovery_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='expense_recovery_percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='fund_accounting_fee_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='fund_accounting_fee_percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='issuer_fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='sma_admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='platformfees',
            name='trustee_fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='platformtierpercs',
            name='percentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='platformtierthresholds',
            name='threshold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
