# Generated by Django 2.2.7 on 2020-11-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0060_auto_20201015_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='ARSN',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
