# Generated by Django 2.2.7 on 2020-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0061_platformnames_arsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnames',
            name='ARSN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
