# Generated by Django 2.2.7 on 2020-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0065_platformnames_direct_pds_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnames',
            name='direct_pds_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
