# Generated by Django 2.2.7 on 2020-12-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0066_auto_20201208_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnames',
            name='fee_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_copiers', to='platforms.PlatformNames'),
        ),
    ]
