# Generated by Django 2.2.7 on 2020-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0051_auto_20200923_1319'),
        ('platforms', '0067_platformnames_fee_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfees',
            name='allowed_investment_classes',
            field=models.ManyToManyField(blank=True, related_name='fee_groups', to='investments.InvestmentClass'),
        ),
    ]
