# Generated by Django 2.2.7 on 2020-12-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0068_platformfees_allowed_investment_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='admin_fee_linking_reduction',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
